Implement IElevator Wrapper 'ElevatorController'
fhhagenberg-sqe-esd-ws21/elevator-control-center-team-c pull request #10
Opened 2021-12-21 15:32 UTC by AnitaMichlits

2021-12-22 08:03 UTC, MikeEdu requested changes

2021-12-22 08:06 UTC, MikeEdu commented on src/main/java/at/fhhagenberg/sqe/ecc/ElevatorController.java
> +            throw(new RuntimeException("Error in setTarget: " + ex.getMessage()));
Test exception throwing of setter methods.

2021-12-22 12:14 UTC, MikeEdu commented on src/main/java/at/fhhagenberg/sqe/ecc/ElevatorController.java
> +public class ElevatorController implements IElevatorController {
Rename `ElevatorController`

2021-12-22 12:14 UTC, MikeEdu commented on src/main/java/at/fhhagenberg/sqe/ecc/ElevatorController.java
> +                    dir = CommittedDirection.UNCOMMITED;
Please, fix my type UNCOMMITED to UNCOMMITTED. :P

2022-01-09 07:49 UTC, AnitaMichlits commented on src/main/java/at/fhhagenberg/sqe/ecc/ElevatorController.java
> +public class ElevatorController implements IElevatorController {
To what should I rename it? any ideas?

2022-01-09 10:11 UTC, MikeEdu approved these changes

2022-01-09 10:12 UTC, merged